name: toktik
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  animate_do: ^4.0.1
  flutter:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.2
  video_player: ^2.9.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/videos/
